# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - data: mp20_only
  - encoder: transformer
  - decoder: transformer
  - autoencoder_module: vae
  - callbacks: autoencoder_mp20_only
  - logger: csv
  - trainer: default
  - paths: default
  - hydra: default
  - _self_

name: ""

# task name, determines output directory path
task_name: "train_autoencoder"

# set False to skip model training
train: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 9
